package(default_visibility = ["//visibility:public"])

cc_test(
    name = "pose_tests",
    srcs = ["pose_tests.cpp"],
    deps = [
        "//source/core/testing:testing_utils",
        "//source/localization:pose",
        "@googletest//:gtest_main",
    ],
)
