package(default_visibility = ["//visibility:public"])

cc_library(
    name = "math",
    srcs = [
        "angle.cpp",
        "geometry.cpp",
    ],
    hdrs = [
        "angle.h",
        "geometry.h",
    ],
    deps = [
        "//source/core:logging",
        "@eigen",
    ],
)
