package(default_visibility = ["//visibility:public"])

cc_test(
    name = "serialization_tests",
    srcs = ["serialization_tests.cpp"],
    deps = [
        "//source/core/bus:serialization",
        "@googletest//:gtest_main",
    ],
)
