package(default_visibility = ["//visibility:public"])

cc_test(
    name = "angle_tests",
    srcs = [
        "angle_tests.cpp",
    ],
    deps = [
        "//source/core/math",
        "//source/core/testing:testing_utils",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "geometry_tests",
    srcs = [
        "geometry_tests.cpp",
    ],
    deps = [
        "//source/core/math",
        "//source/core/testing:testing_utils",
        "@googletest//:gtest_main",
    ],
)
