package(default_visibility = ["//visibility:public"])

cc_library(
    name = "geometry",
    srcs = ["geometry.cpp"],
    hdrs = ["geometry.h"],
    deps = [
        "//source/core:logging",
        "@eigen",
    ],
)
