package(default_visibility = ["//visibility:public"])

cc_library(
    name = "testing_utils",
    hdrs = ["assertions.h"],
    deps = [
        "//source/core/math",
        "//source/localization:pose",
        "@googletest//:gtest_main",
    ],
)
