package(default_visibility = ["//visibility:public"])

cc_test(
    name = "geometry_tests",
    srcs = ["geometry_tests.cpp"],
    deps = [
        "//source/core/geometry",
        "//source/core/testing:testing_utils",
        "@googletest//:gtest_main",
    ],
)
