package(default_visibility = ["//visibility:public"])

cc_test(
    name = "planner_tests",
    srcs = ["planner_tests.cpp"],
    deps = [
        "//source/core/testing:testing_utils",
        "//source/planning:planner",
        "@googletest//:gtest_main",
    ],
)
